language: node_js
node_js:
  - 12
cache: npm
install:
  - yarn install
jobs:
  include:
    - stage: Test
      script:
        - npm run test
        - npm run build
    - stage: Release
      script: npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        skip_cleanup: true
branches:
  only:
    - master
